#!/bin/bash
cd ~/Mermaid\'s\ Rest/programs/Muirgen
# root owned stuff
rsync -av ./muirgen.sql root@mr-scifi-ui:/root/
rsync -av ./nginx/* root@mr-scifi-ui:/etc/nginx/conf.d/
# user owned stuff
rsync -av ./fui/package.json admin@mr-scifi-ui:/home/admin/fui/
rsync -av ./fui/config.js admin@mr-scifi-ui:/home/admin/fui/
rsync -av --exclude='node_modules' ./fui/frontend/* admin@mr-scifi-ui:/home/admin/fui/frontend/
rsync -av ./fui/backend/* admin@mr-scifi-ui:/home/admin/fui/backend/
# recompile
#ssh admin@mr-scifi-ui "cd /home/admin/fui && npm install && npm run build && pm2 restart fui"
