[package]
name = "muirgen-n2kd"
version = "0.1.0"
edition = "2024"

[dependencies]
deku = "0.17"
dotenvy = "0.15"
futures-util = "0.3"
rumqttc = "0.24"
serde_json = "1.0"
socketcan = { version = "3", features = ["tokio"] }
sqlx = { version = "0.8", features = ["macros", "postgres", "runtime-tokio-rustls", "uuid"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v7"]}
